# Generated by Django 4.2.5 on 2023-09-12 03:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
